services:
  # Sonata Admin
  admin.customer:
    class: AppBundle\Admin\CustomerAdmin
    arguments: [ ~, AppBundle\Entity\Customer, AppBundle:CustomerAdmin, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Cliente", group: "Client", label_translator_strategy: "sonata.admin.label.strategy.noop" }
  admin.state:
    class: AppBundle\Admin\StateAdmin
    arguments: [ ~, AppBundle\Entity\State, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Provincia", group: "Client", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
  admin.user:
    class: AppBundle\Admin\UserAdmin
    arguments: [ ~, AppBundle\Entity\User, AppBundle:UserAdmin, "@fos_user.user_manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Usuario", group: "Client", label_translator_strategy: "sonata.admin.label.strategy.noop" }
  admin.windfarm:
    class: AppBundle\Admin\WindfarmAdmin
    arguments: [ ~, AppBundle\Entity\Windfarm, AppBundle:WindfarmAdmin, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Parque Eólico", group: "Windfarm", label_translator_strategy: "sonata.admin.label.strategy.noop" }
  admin.windmill:
    class: AppBundle\Admin\WindmillAdmin
    arguments: [ ~, AppBundle\Entity\Windmill, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Aerogenerador", group: "Windfarm", label_translator_strategy: "sonata.admin.label.strategy.noop" }
  admin.turbine:
    class: AppBundle\Admin\TurbineAdmin
    arguments: [ ~, AppBundle\Entity\Turbine, AppBundle:TurbineAdmin, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Turbina", group: "Windfarm", label_translator_strategy: "sonata.admin.label.strategy.noop" }
  admin.blade:
    class: AppBundle\Admin\BladeAdmin
    arguments: [ ~, AppBundle\Entity\Blade, AppBundle:BladeAdmin, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Tipo Pala", group: "Windfarm", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
  admin.windmill_blade:
    class: AppBundle\Admin\WindmillBladeAdmin
    arguments: [ ~, AppBundle\Entity\WindmillBlade, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Palas", group: "Windfarm", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
  admin.audit:
    class: AppBundle\Admin\AuditAdmin
    arguments: [ ~, AppBundle\Entity\Audit, AppBundle:AuditAdmin, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Inspección", group: "Audit", label_translator_strategy: "sonata.admin.label.strategy.noop" }
  admin.blade_damage:
    class: AppBundle\Admin\BladeDamageAdmin
    arguments: [ ~, AppBundle\Entity\BladeDamage, AppBundle:BladeDamageAdmin, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Daño Pala", group: "Audit", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
  admin.damage:
    class: AppBundle\Admin\DamageAdmin
    arguments: [ ~, AppBundle\Entity\Damage, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Tipo Daño", group: "Audit", label_translator_strategy: "sonata.admin.label.strategy.noop" }
  admin.damage_category:
    class: AppBundle\Admin\DamageCategoryAdmin
    arguments: [ ~, AppBundle\Entity\DamageCategory, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Categoría Daño", group: "Audit", label_translator_strategy: "sonata.admin.label.strategy.noop" }
  admin.photo:
    class: AppBundle\Admin\PhotoAdmin
    arguments: [ ~, AppBundle\Entity\Photo, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Foto", group: "Audit", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
  admin.blade_photo:
    class: AppBundle\Admin\BladePhotoAdmin
    arguments: [ ~, AppBundle\Entity\BladePhoto, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Foto Pala", group: "Audit", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
  admin.observation:
    class: AppBundle\Admin\ObservationAdmin
    arguments: [ ~, AppBundle\Entity\Observation, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Observaciones", group: "Audit", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
  admin.audit_windmill_blade:
    class: AppBundle\Admin\AuditWindmillBladeAdmin
    arguments: [ ~, AppBundle\Entity\AuditWindmillBlade, AppBundle:AuditWindmillBladeAdmin, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Audit Daño Pala", group: "Audit", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
  admin.work_order:
    class: AppBundle\Admin\WorkOrderAdmin
    arguments: [~, AppBundle\Entity\WorkOrder, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Proyecto", group: "WorkOrder", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: true }
  #        calls:
  #            - [ setTemplate, [ edit, "::Admin/WorkOrder/edit.html.twig" ] ]
  admin.work_order_task:
    class: AppBundle\Admin\WorkOrderTaskAdmin
    arguments: [~, AppBundle\Entity\WorkOrderTask, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Tareas", group: "WorkOrder", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: true }
  admin.vehicle:
    class: AppBundle\Admin\VehicleAdmin
    arguments: [~, AppBundle\Entity\Vehicle, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Vehículos", group: "WorkOrder", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: true }
  admin.delivery_note:
    class: AppBundle\Admin\DeliveryNoteAdmin
    arguments: [~, AppBundle\Entity\DeliveryNote, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Albarán", group: "WorkOrder", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: true }
  admin.delivery_note_time_register:
    class: AppBundle\Admin\DeliveryNoteTimeRegisterAdmin
    arguments: [~, AppBundle\Entity\DeliveryNoteTimeRegister, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Fichajes", group: "WorkOrder", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: true }
  admin.non_standard_used_material:
    class: AppBundle\Admin\NonStandardUsedMaterialAdmin
    arguments: [~, AppBundle\Entity\NonStandardUsedMaterial, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Materiales no est. utilizados", group: "WorkOrder", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: true }
  admin.worker_timesheet:
    class: AppBundle\Admin\WorkerTimesheetAdmin
    arguments: [~, AppBundle\Entity\WorkerTimesheet, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Partes de trabajo", group: "WorkOrder", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: true }
  admin.presence_monitoring:
    class: AppBundle\Admin\PresenceMonitoringAdmin
    arguments: [~, AppBundle\Entity\PresenceMonitoring, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Registros", group: "PresenceMonitoring", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: true }

  # Sonata Blocks
  admin.block.audits:
    class: AppBundle\Admin\Block\AuditsBlock
    tags:
      - { name: sonata.block }
    arguments: [ "sonata.admin.block.audits", "@templating", "@doctrine.orm.entity_manager", "@app.auth_customer" ]
