imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false
doctrine:
    orm:
        metadata_cache_driver:       apcu
        query_cache_driver:          apcu

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [ !event ]
        console:
            type:   console
            channels: [ !event, !doctrine ]

cypress_git_elephant:
    enable_profiler: false
    profiler_repository_path: "%kernel.root_dir%/../"
    repositories:
        "Fibervent": "%kernel.root_dir%/../"

swiftmailer:
    delivery_address: "%dev_delivery_address%"
