# Vich Uploader
vich_uploader:
    db_driver: orm
    mappings:
        image:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images
            upload_destination: "%kernel.root_dir%/../web/uploads/images"

# Liip Imagine
liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        60x60:
            quality: 95
            filters:
                thumbnail: { size: [60, 60], mode: outbound }
