# Vich Uploader
vich_uploader:
    db_driver: orm
    mappings:
        image:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/image
            upload_destination: "%kernel.root_dir%/../web/uploads/images/image"
        user:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/user
            upload_destination: "%kernel.root_dir%/../web/uploads/images/user"

# Liip Imagine
liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        480xY:
            quality: 95
            filters:
                thumbnail: { size: [ 480, null ], mode: outbound }
        60x60:
            quality: 100
            filters:
                thumbnail: { size: [ 60, 60 ], mode: outbound }
