services:
    app.state_repository:
        class: AppBundle\Repository\StateRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:State
    app.turbine_repository:
        class: AppBundle\Repository\TurbineRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Turbine
