services:
    app.state_repository:
        class: AppBundle\Repository\StateRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:State
    app.turbine_repository:
        class: AppBundle\Repository\TurbineRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Turbine
    app.blade_repository:
        class: AppBundle\Repository\BladeRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Blade
    app.blade_damage_repository:
        class: AppBundle\Repository\BladeDamageRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:BladeDamage
    app.windfarm_repository:
        class: AppBundle\Repository\WindfarmRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Windfarm
    app.windmill_repository:
        class: AppBundle\Repository\WindmillRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Windmill
    app.user_repository:
        class: AppBundle\Repository\UserRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:User
    app.customer_repository:
        class: AppBundle\Repository\CustomerRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Customer
    app.damage_repository:
        class: AppBundle\Repository\DamageRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Damage
    app.damage_category_repository:
        class: AppBundle\Repository\DamageCategoryRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:DamageCategory
    app.audit_repository:
        class: AppBundle\Repository\AuditRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Audit
    app.windmill_blade_repository:
        class: AppBundle\Repository\WindmillBladeRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:WindmillBlade
    app.observation_repository:
        class: AppBundle\Repository\ObservationRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Observation
    app.repositories_service:
        class: AppBundle\Service\RepositoriesService
        arguments:
            - "@app.customer_repository"
            - "@app.user_repository"
            - "@app.windmill_repository"
            - "@app.windfarm_repository"
            - "@app.blade_repository"
            - "@app.turbine_repository"
            - "@app.state_repository"
            - "@app.damage_repository"
            - "@app.damage_category_repository"
            - "@app.audit_repository"
            - "@app.windmill_blade_repository"
            - "@app.blade_damage_repository"
