services:
    app.state_repository:
        class: AppBundle\Repository\StateRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:State
    app.turbine_repository:
        class: AppBundle\Repository\TurbineRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Turbine
    app.blade_repository:
        class: AppBundle\Repository\BladeRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Blade
    app.windfarm_repository:
        class: AppBundle\Repository\WindfarmRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Windfarm
    app.windmill_repository:
        class: AppBundle\Repository\WindmillRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:Windmill
    app.user_repository:
        class: AppBundle\Repository\UserRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - AppBundle:User
