sonata:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   /admin

_sonata_admin:
    resource: .
    type:     sonata_admin
    prefix:   /admin

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix:   /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix:   /admin/resetting

#sonata_user_profile:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
#    prefix: /admin/profile

#sonata_user_change_password:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
#    prefix: /admin/profile

app_front:
    resource: '@AppBundle/Controller'
    type:     annotation
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
