imports:
    - { resource: repositories.yml }
    - { resource: admins.yml }

services:
# PDF service builders
    app.custom_tcpdf:
        class: AppBundle\Pdf\CustomTcpdf
        arguments:
            - "@app.smart_assets_helper"
            - "@translator.default"
            - AppBundle\Entity\Windfarm
    app.audit_pdf_builder:
        class: AppBundle\Service\AuditPdfBuilderService
        arguments:
            - "@white_october.tcpdf"
            - "@liip_imagine.cache.manager"
            - "@vich_uploader.templating.helper.uploader_helper"
            - "@app.smart_assets_helper"
            - "@translator.default"
            - "@app.damage_repository"
            - "@app.damage_category_repository"
            - "@app.blade_damage_repository"
            - "@app.customer_repository"
            - "@app.audit_model_diagram_bridge"
            - "@app.windfarm_builder_bridge"
            - "@app.factory_windfarm_blades_damages_helper"
            - "@app.manager_observation"
    app.windfarm_audits_pdf_builder:
        class: AppBundle\Service\WindfarmAuditsPdfBuilderService
        arguments:
            - "@white_october.tcpdf"
            - "@liip_imagine.cache.manager"
            - "@vich_uploader.templating.helper.uploader_helper"
            - "@app.smart_assets_helper"
            - "@translator.default"
            - "@app.damage_repository"
            - "@app.damage_category_repository"
            - "@app.blade_damage_repository"
            - "@app.customer_repository"
            - "@app.audit_model_diagram_bridge"
            - "@app.windfarm_builder_bridge"
            - "@app.factory_windfarm_blades_damages_helper"
            - "@app.manager_observation"
    app.audit_model_diagram_bridge:
        class: AppBundle\Service\AuditModelDiagramBridgeService
    app.windfarm_builder_bridge:
        class: AppBundle\Service\WindfarmBuilderBridgeService
        arguments:
            - "@translator.default"

# Form types
    app.form_type_action_button:
        class: AppBundle\Form\Type\ActionButtonFormType
        tags:
            - { name: form.type, alias: action_button }
    app.form_type_windfarm_annual_stats:
        class: AppBundle\Form\Type\WindfarmAnnualStatsFormType
        tags:
            - { name: form.type }
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.audit_repository"
            - "@app.damage_category_repository"
    app.form_type_windfarm_audit_stats:
        class: AppBundle\Form\Type\WindfarmAuditStatsFormType
        tags:
            - { name: form.type }
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.audit_repository"
# Messaging
    app.courier:
        class: AppBundle\Service\CourierService
        arguments:
            - "@swiftmailer.mailer"
    app.notification:
        class: AppBundle\Service\NotificationService
        arguments:
            - "@app.courier"

# Auth
    app.auth_customer:
        class: AppBundle\Service\AuthCustomerService
        arguments:
            - "@security.authorization_checker"
            - "@security.token_storage"

# Factory
    app.factory_windfarm_blades_damages_helper:
        class: AppBundle\Factory\WindmillBladesDamagesHelperFactory
        arguments:
            - "@app.damage_category_repository"
    app.smart_assets_helper:
        class: AppBundle\Service\SmartAssetsHelperService
        arguments:
            - "@kernel"
            - "%project_url_base%"

# Manager
    app.manager_observation:
        class: AppBundle\Manager\ObservationManager
        arguments:
            - "@app.blade_damage_repository"
    app.manager_customer_ajax_response:
        class: AppBundle\Manager\CustomerAjaxResponseManager
        arguments:
            - "@app.audit_repository"
    app.manager_work_order:
        class: AppBundle\Manager\WorkOrderManager
        arguments:
            - "@doctrine.orm.entity_manager"

# Twig
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
            - "@app.damage_repository"
            - "@app.factory_windfarm_blades_damages_helper"

# Event listeners
    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments:
            - "%locale%"
        tags:
            - { name: kernel.event_subscriber }
    app.user_login_locale_listener:
        class: AppBundle\EventListener\UserLoginLocaleListener
        arguments:
            - "@session"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
