services:
# Sonata Admin
    admin.customer:
        class: AppBundle\Admin\CustomerAdmin
        arguments: [ ~ , AppBundle\Entity\Customer , ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Cliente", group: "Customer" }
    admin.country:
        class: AppBundle\Admin\CountryAdmin
        arguments: [ ~ , AppBundle\Entity\Country , ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "País", group: "Customer", show_in_dashboard: false }
    admin.state:
        class: AppBundle\Admin\StateAdmin
        arguments: [ ~ , AppBundle\Entity\State , ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Província", group: "Customer", show_in_dashboard: false }
