imports:
    - { resource: repositories.yml }

services:
# Sonata Admin
    admin.customer:
        class: AppBundle\Admin\CustomerAdmin
        arguments: [ ~, AppBundle\Entity\Customer, ~, "@app.state_repository", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Client", group: "Client" }
    admin.state:
        class: AppBundle\Admin\StateAdmin
        arguments: [ ~, AppBundle\Entity\State, ~, "@app.state_repository", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Província", group: "Customer", show_in_dashboard: false }
    admin.windfarm:
        class: AppBundle\Admin\WindfarmAdmin
        arguments: [ ~, AppBundle\Entity\Windfarm, ~, "@app.state_repository", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Parc Eòlic", group: "Parc_Eolic" }
    admin.windmill:
        class: AppBundle\Admin\WindmillAdmin
        arguments: [ ~, AppBundle\Entity\Windmill, ~, "@app.state_repository", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Aerogenerador", group: "Parc_Eolic" }
    admin.turbine:
        class: AppBundle\Admin\TurbineAdmin
        arguments: [ ~, AppBundle\Entity\Turbine, ~, "@app.state_repository", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Turbina", group: "Parc_Eolic", show_in_dashboard: false }
    admin.blade:
        class: AppBundle\Admin\BladeAdmin
        arguments: [ ~, AppBundle\Entity\Blade, ~, "@app.state_repository", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tipus Pala", group: "Parc_Eolic", show_in_dashboard: false }
    admin.windmillblade:
        class: AppBundle\Admin\WindmillBladeAdmin
        arguments: [ ~, AppBundle\Entity\WindmillBlade, ~, "@app.state_repository", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Pales", group: "Parc_Eolic", show_in_dashboard: false }
    admin.audit:
        class: AppBundle\Admin\AuditAdmin
        arguments: [ ~, AppBundle\Entity\Audit, ~, "@app.state_repository", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Auditoria", group: "Auditoria" }
    admin.damage:
        class: AppBundle\Admin\DamageAdmin
        arguments: [ ~, AppBundle\Entity\Damage, ~, "@app.state_repository", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Danys", group: "Auditoria" }
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~, "@fos_user.user_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Usuari", group: "Client" }
