services:
# Sonata Admin
    admin.customer:
        class: AppBundle\Admin\CustomerAdmin
        arguments: [ ~ , AppBundle\Entity\Customer , ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Cliente", group: "Customer" }
