imports:
    - { resource: repositories.yml }

services:
# Sonata Admin
    admin.customer:
        class: AppBundle\Admin\CustomerAdmin
        arguments: [ ~, AppBundle\Entity\Customer, AppBundle:CustomerAdmin, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Cliente", group: "Client", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.state:
        class: AppBundle\Admin\StateAdmin
        arguments: [ ~, AppBundle\Entity\State, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Provincia", group: "Client", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, AppBundle:UserAdmin, "@fos_user.user_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Usuario", group: "Client", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.windfarm:
        class: AppBundle\Admin\WindfarmAdmin
        arguments: [ ~, AppBundle\Entity\Windfarm, AppBundle:WindfarmAdmin, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Parque Eólico", group: "Windfarm", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.windmill:
        class: AppBundle\Admin\WindmillAdmin
        arguments: [ ~, AppBundle\Entity\Windmill, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Aerogenerador", group: "Windfarm", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.turbine:
        class: AppBundle\Admin\TurbineAdmin
        arguments: [ ~, AppBundle\Entity\Turbine, AppBundle:TurbineAdmin, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Turbina", group: "Windfarm", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.blade:
        class: AppBundle\Admin\BladeAdmin
        arguments: [ ~, AppBundle\Entity\Blade, AppBundle:BladeAdmin, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tipo Pala", group: "Windfarm", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
    admin.windmill_blade:
        class: AppBundle\Admin\WindmillBladeAdmin
        arguments: [ ~, AppBundle\Entity\WindmillBlade, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Palas", group: "Windfarm", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
    admin.audit:
        class: AppBundle\Admin\AuditAdmin
        arguments: [ ~, AppBundle\Entity\Audit, AppBundle:AuditAdmin, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Inspección", group: "Audit", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.blade_damage:
        class: AppBundle\Admin\BladeDamageAdmin
        arguments: [ ~, AppBundle\Entity\BladeDamage, AppBundle:BladeDamageAdmin, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Daño Pala", group: "Audit", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
    admin.damage:
        class: AppBundle\Admin\DamageAdmin
        arguments: [ ~, AppBundle\Entity\Damage, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tipo Daño", group: "Audit", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.damage_category:
        class: AppBundle\Admin\DamageCategoryAdmin
        arguments: [ ~, AppBundle\Entity\DamageCategory, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Categoría Daño", group: "Audit", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    admin.photo:
        class: AppBundle\Admin\PhotoAdmin
        arguments: [ ~, AppBundle\Entity\Photo, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Foto", group: "Audit", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
    admin.blade_photo:
        class: AppBundle\Admin\BladePhotoAdmin
        arguments: [ ~, AppBundle\Entity\BladePhoto, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Foto Pala", group: "Audit", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
    admin.observation:
        class: AppBundle\Admin\ObservationAdmin
        arguments: [ ~, AppBundle\Entity\Observation, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Observaciones", group: "Audit", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
    admin.audit_windmill_blade:
        class: AppBundle\Admin\AuditWindmillBladeAdmin
        arguments: [ ~, AppBundle\Entity\AuditWindmillBlade, AppBundle:AuditWindmillBladeAdmin, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Audit Daño Pala", group: "Audit", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
    admin.work_order:
        class: AppBundle\Admin\WorkOrderAdmin
        arguments: [~, AppBundle\Entity\WorkOrder, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Proyecto", group: "WorkOrder", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: true }
    admin.work_order_task:
        class: AppBundle\Admin\WorkOrderTaskAdmin
        arguments: [~, AppBundle\Entity\WorkOrderTask, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tareas", group: "WorkOrder", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: true }
    admin.vehicle:
        class: AppBundle\Admin\VehicleAdmin
        arguments: [~, AppBundle\Entity\Vehicle, ~, "@security.authorization_checker", "@security.token_storage", "@app.repositories_service", "@vich_uploader.templating.helper.uploader_helper", "@liip_imagine.cache.manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Vehículos", group: "WorkOrder", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: true }

    # Sonata Blocks
    admin.block.audits:
        class: AppBundle\Admin\Block\AuditsBlock
        tags:
            - { name: sonata.block }
        arguments: [ "sonata.admin.block.audits", "@templating", "@doctrine.orm.entity_manager", "@app.auth_customer" ]

# PDF service builders
    app.custom_tcpdf:
        class: AppBundle\Pdf\CustomTcpdf
        arguments:
            - "@app.smart_assets_helper"
            - "@translator.default"
            - AppBundle\Entity\Windfarm
    app.audit_pdf_builder:
        class: AppBundle\Service\AuditPdfBuilderService
        arguments:
            - "@white_october.tcpdf"
            - "@liip_imagine.cache.manager"
            - "@vich_uploader.templating.helper.uploader_helper"
            - "@app.smart_assets_helper"
            - "@translator.default"
            - "@app.damage_repository"
            - "@app.damage_category_repository"
            - "@app.blade_damage_repository"
            - "@app.customer_repository"
            - "@app.audit_model_diagram_bridge"
            - "@app.windfarm_builder_bridge"
            - "@app.factory_windfarm_blades_damages_helper"
            - "@app.manager_observation"
    app.windfarm_audits_pdf_builder:
        class: AppBundle\Service\WindfarmAuditsPdfBuilderService
        arguments:
            - "@white_october.tcpdf"
            - "@liip_imagine.cache.manager"
            - "@vich_uploader.templating.helper.uploader_helper"
            - "@app.smart_assets_helper"
            - "@translator.default"
            - "@app.damage_repository"
            - "@app.damage_category_repository"
            - "@app.blade_damage_repository"
            - "@app.customer_repository"
            - "@app.audit_model_diagram_bridge"
            - "@app.windfarm_builder_bridge"
            - "@app.factory_windfarm_blades_damages_helper"
            - "@app.manager_observation"
    app.audit_model_diagram_bridge:
        class: AppBundle\Service\AuditModelDiagramBridgeService
    app.windfarm_builder_bridge:
        class: AppBundle\Service\WindfarmBuilderBridgeService
        arguments:
            - "@translator.default"

# Form types
    app.form_type_action_button:
        class: AppBundle\Form\Type\ActionButtonFormType
        tags:
            - { name: form.type, alias: action_button }
    app.form_type_windfarm_annual_stats:
        class: AppBundle\Form\Type\WindfarmAnnualStatsFormType
        tags:
            - { name: form.type }
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.audit_repository"
            - "@app.damage_category_repository"
    app.form_type_windfarm_audit_stats:
        class: AppBundle\Form\Type\WindfarmAuditStatsFormType
        tags:
            - { name: form.type }
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.audit_repository"
# Messaging
    app.courier:
        class: AppBundle\Service\CourierService
        arguments:
            - "@swiftmailer.mailer"
    app.notification:
        class: AppBundle\Service\NotificationService
        arguments:
            - "@app.courier"

# Auth
    app.auth_customer:
        class: AppBundle\Service\AuthCustomerService
        arguments:
            - "@security.authorization_checker"
            - "@security.token_storage"

# Factory
    app.factory_windfarm_blades_damages_helper:
        class: AppBundle\Factory\WindmillBladesDamagesHelperFactory
        arguments:
            - "@app.damage_category_repository"
    app.smart_assets_helper:
        class: AppBundle\Service\SmartAssetsHelperService
        arguments:
            - "@kernel"
            - "%project_url_base%"

# Manager
    app.manager_observation:
        class: AppBundle\Manager\ObservationManager
        arguments:
            - "@app.blade_damage_repository"

# Twig
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
            - "@app.damage_repository"
            - "@app.factory_windfarm_blades_damages_helper"

# Event listeners
    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments:
            - "%locale%"
        tags:
            - { name: kernel.event_subscriber }
    app.user_login_locale_listener:
        class: AppBundle\EventListener\UserLoginLocaleListener
        arguments:
            - "@session"
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
