services:
# Sonata Admin
    admin.customer:
        class: AppBundle\Admin\CustomerAdmin
        arguments: [ ~ , AppBundle\Entity\Customer , ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Client", group: "Client" }
    admin.country:
        class: AppBundle\Admin\CountryAdmin
        arguments: [ ~ , AppBundle\Entity\Country , ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "País", group: "Customer", show_in_dashboard: false }
    admin.state:
        class: AppBundle\Admin\StateAdmin
        arguments: [ ~ , AppBundle\Entity\State , ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Província", group: "Customer", show_in_dashboard: false }
    admin.windfarm:
        class: AppBundle\Admin\WindfarmAdmin
        arguments: [ ~ , AppBundle\Entity\Windfarm , ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Parc Eòlic", group: "Parc Eòlic" }
    admin.windmill:
        class: AppBundle\Admin\WindmillAdmin
        arguments: [ ~ , AppBundle\Entity\Windmill , ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Aerogenerador", group: "Parc Eòlic" }
    admin.turbine:
        class: AppBundle\Admin\TurbineAdmin
        arguments: [ ~ , AppBundle\Entity\Turbine , ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Turbina", group: "Parc Eòlic", show_in_dashboard: false }
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [ ~, AppBundle\Entity\User, ~, "@fos_user.user_manager" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Usuari", group: "Client" }
