# Block
sonata_block:
    default_contexts: [ cms ]
    blocks:
        sonata.admin.block.admin_list:  ~
        sonata.user.block.menu:         ~
        sonata.block.service.text:      ~

# User
sonata_user:
    security_acl: true
    manager_type: orm

# Admin
sonata_admin:
    title: "%project_web_title%"
    title_logo: "/bundles/app/images/fibervent_logo_black_landscape.jpg"
    options:
        html5_validate: true
        confirm_exit:   true
        use_select2:    true
        pager_links:    10
    persist_filters: true
    security:
        handler: sonata.admin.security.handler.role
    templates:
        layout: "::Admin/layout.html.twig"
    dashboard:
        groups:
            Client:
                icon: "<i class='fa fa-industry' aria-hidden='true'></i>"
            Parc_Eolic:
                icon: "<i class='fa fa-bolt' aria-hidden='true'></i>"
                label: "Parc Eòlic"
        blocks:
            -
                position: top
                type: sonata.block.service.text
                class: col-md-12
                settings:
                    content: >
                        <h1 class="text-center" style="margin:0 0 25px 0">%project_web_title%</h1>
            -
                position: top
                type: sonata.admin.block.admin_list
                class: col-md-6
                settings:
                    groups: [ Client ]
            -
                position: top
                type: sonata.admin.block.admin_list
                class: col-md-6
                settings:
                    groups: [ Parc_Eolic ]
